### PR TITLE
Article about fonts

### PR DESCRIPTION
**Pull request by Lemmih**

### CODE REVIEW

**Comment by cobordism** [comment]
Question: What would it take to be able to choose any font listed here: http://jf.burnol.free.fr/showcase.html ?

PS 
demo for manim https://vimeo.com/435684836
Note - it requires latex, xelatex and lualatex.

**Comment by Lemmih** [comment]
It wouldn't take much. Reanimate can use any LaTeX font. I'll write the article about how to use fonts soonish. If you wanna get your hands dirty, see the 'latexWithHeaders' function from Reanimate.LaTeX.

**Comment by cobordism** [comment]
> If you wanna get your hands dirty

I might try once I'm a little more comfortable with how everything works.

Also, I've never Haskelled before. :-/

The point I was making about http://jf.burnol.free.fr/showcase.html is that it takes much more than just loading some latex packages. Many fonts require their own latex templates along with configuration options like compiler (lualatex / xelatex / pdflatex etc) and output (dvi / xdv / pdf).

**Comment by Lemmih** [comment]
Ah, then it might be a bit more involved. But if it can be done in manim then it can also be done in reanimate.

**Pull request merged**
